<a href="https://colab.research.google.com/github/Raj-tony/ML_2021/blob/main/something.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
arr = np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
arr[arr<4]=-1
print(arr)

[[-1 -1 -1 -1  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
sin_arr = np.sin(arr)*10
print(sin_arr)

[[-8.41470985 -8.41470985 -8.41470985 -8.41470985 -7.56802495]
 [-9.58924275 -2.79415498  6.56986599  9.89358247  4.12118485]
 [-5.44021111 -9.99990207 -5.36572918  4.20167037  9.90607356]
 [ 6.5028784  -2.87903317 -9.61397492 -7.50987247  1.4987721 ]]


In [9]:
a = arr[1:3,1]
print(a)

[ 6 11]


In [11]:
b = arr[-1,-1]
print(b)

19


In [12]:
c = arr.T
print(c)

[[-1  5 10 15]
 [-1  6 11 16]
 [-1  7 12 17]
 [-1  8 13 18]
 [ 4  9 14 19]]


In [22]:
s = arr.reshape(2,10)
print(s)

[[-1 -1 -1 -1  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [23]:
f = arr[-1::]
print(f)

[[15 16 17 18 19]]


In [26]:
for i in arr.flat:
  print(i)

-1
-1
-1
-1
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [27]:
for i in arr.flat:
  print(i)

-1
-1
-1
-1
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [28]:
import numpy as np
import pandas as pd


# New Section